language: node_js
node_js:
  - "0.11"

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install && node_modules/bower/bin/bower install

script: 
  - node_modules/karma/bin/karma start --single-run --browsers PhantomJS
